var mongoose = require('mongoose');

var ProjectSchema = new mongoose.Schema({
    projectNumber: Number ,	
    organizationId: String,	
    name: String, 
    description: String,	
    duration: Number,
    scope: String,	
    childrenProfile: String,	
    ages: String,
    totalSpace: Number,	
    availableSpace: Number,	
    coordinatorName: String,	
    coordinatorPhone: String,	
    coordinatorEmail: String,
    coordinatorCelPhone: String,
    postalCode: String,
    department: String,
    observations: String,
    abandonment: Boolean,	
    legalRepresentativeAbsence: Boolean,	
    abuseBySupression: Boolean,	
    abuseByTransgression: Boolean,	
    lackOfBasicNeeds: Boolean,	
    threatToHeritage: Boolean,	
    addiction: Boolean,	
    sexualFreedomVictims: Boolean,	
    sexualHarassmentVictims: Boolean,	
    procuring: Boolean,	
    trafficking: Boolean, 	
    publicSexualExposure: Boolean,	
    pornography: Boolean,
    sexualTurism: Boolean,	
    criminalRecruitmentRisk: Boolean,	
    begging: Boolean,	
    economicExploitation: Boolean,	
    childAbduction: Boolean,	
    childrenDinning: Boolean,	
    preBasicEducationCenter: Boolean,	
    sportEducationCenter: Boolean,	
    alternativeEducationCenter: Boolean,	
    initialEducationAndEarlyEstimulationCenter: Boolean,	
    artisticFormationCenter: Boolean,
    others: Boolean
});

module.exports = mongoose.model('Project', ProjectSchema);